version: '3.8'

services:
  server:
    build: 
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      # Mantém o banco de dados persistente em um Volume isolado do Docker
      - sqlite_data:/app/db_data
      # Acesso ao Socket do Docker para permitir auto-atualização
      - /var/run/docker.sock:/var/run/docker.sock
      # Mapeia a raiz do projeto no host para o container poder rodar git pull
      - .:/app/host_source
    user: root
    environment:
      - NODE_ENV=production
      - JWT_SECRET=sua_chave_secreta_super_segura
    restart: always

  client:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always

volumes:
  sqlite_data:
